version: "3"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/local/html
      - ./nginx/conf.d/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/conf.d/www.conf:/usr/local/nginx/conf/vhost/www.conf
    networks:
      - frontend
    restart: always
    container_name: nginx
    depends_on:
      - php

  php:
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./php/conf.d/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - frontend
      - backend
    restart: always
    container_name: php

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis.conf
      - ./redis/data:/data
    networks:
      - backend
    restart: always
    container_name: redis
networks:
  frontend:
  backend:
